

class ConfigJogo:
    LARGURA_TELA = 600
    ALTURA_TELA = 400
    COR_BARRA = (0, 0, 0)
    COR_BOLA = (0, 0, 0)
    COR_ESTADO = (0, 0, 255)
    COR_TITULO = (0, 0, 0)
    VELOCIDADE_BOLA = 0.15
    VELOCIDADE_BARRAS = 0.2
    LARGURA_BARRA = (0.02 * LARGURA_TELA)
    ALTURA_BARRA = (0.2 * ALTURA_TELA)
    RAIO_BOLA = (0.02 * ALTURA_TELA)
    POS_X_BARRA_ESQUERDA = (0.1 * LARGURA_TELA)
    POS_X_BARRA_DIREITA = (0.9 * LARGURA_TELA - LARGURA_BARRA)
    ALTURA_PLACAR = 0.1 * ALTURA_TELA
    ALTURA_TEMPO = 0.15 * ALTURA_TELA
    DURACAO_PARTIDA = 30
    FONTE_TITULO = 72
    FONTE_SUBTITULO = 36
